version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 200000000stake
- name: bob
  coins:
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
