// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package hypergridssn

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_HypergridNode           protoreflect.MessageDescriptor
	fd_HypergridNode_pubkey    protoreflect.FieldDescriptor
	fd_HypergridNode_name      protoreflect.FieldDescriptor
	fd_HypergridNode_rpc       protoreflect.FieldDescriptor
	fd_HypergridNode_role      protoreflect.FieldDescriptor
	fd_HypergridNode_starttime protoreflect.FieldDescriptor
	fd_HypergridNode_creator   protoreflect.FieldDescriptor
)

func init() {
	file_hypergridssn_hypergridssn_hypergrid_node_proto_init()
	md_HypergridNode = File_hypergridssn_hypergridssn_hypergrid_node_proto.Messages().ByName("HypergridNode")
	fd_HypergridNode_pubkey = md_HypergridNode.Fields().ByName("pubkey")
	fd_HypergridNode_name = md_HypergridNode.Fields().ByName("name")
	fd_HypergridNode_rpc = md_HypergridNode.Fields().ByName("rpc")
	fd_HypergridNode_role = md_HypergridNode.Fields().ByName("role")
	fd_HypergridNode_starttime = md_HypergridNode.Fields().ByName("starttime")
	fd_HypergridNode_creator = md_HypergridNode.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_HypergridNode)(nil)

type fastReflection_HypergridNode HypergridNode

func (x *HypergridNode) ProtoReflect() protoreflect.Message {
	return (*fastReflection_HypergridNode)(x)
}

func (x *HypergridNode) slowProtoReflect() protoreflect.Message {
	mi := &file_hypergridssn_hypergridssn_hypergrid_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_HypergridNode_messageType fastReflection_HypergridNode_messageType
var _ protoreflect.MessageType = fastReflection_HypergridNode_messageType{}

type fastReflection_HypergridNode_messageType struct{}

func (x fastReflection_HypergridNode_messageType) Zero() protoreflect.Message {
	return (*fastReflection_HypergridNode)(nil)
}
func (x fastReflection_HypergridNode_messageType) New() protoreflect.Message {
	return new(fastReflection_HypergridNode)
}
func (x fastReflection_HypergridNode_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_HypergridNode
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_HypergridNode) Descriptor() protoreflect.MessageDescriptor {
	return md_HypergridNode
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_HypergridNode) Type() protoreflect.MessageType {
	return _fastReflection_HypergridNode_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_HypergridNode) New() protoreflect.Message {
	return new(fastReflection_HypergridNode)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_HypergridNode) Interface() protoreflect.ProtoMessage {
	return (*HypergridNode)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_HypergridNode) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Pubkey != "" {
		value := protoreflect.ValueOfString(x.Pubkey)
		if !f(fd_HypergridNode_pubkey, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_HypergridNode_name, value) {
			return
		}
	}
	if x.Rpc != "" {
		value := protoreflect.ValueOfString(x.Rpc)
		if !f(fd_HypergridNode_rpc, value) {
			return
		}
	}
	if x.Role != int32(0) {
		value := protoreflect.ValueOfInt32(x.Role)
		if !f(fd_HypergridNode_role, value) {
			return
		}
	}
	if x.Starttime != int32(0) {
		value := protoreflect.ValueOfInt32(x.Starttime)
		if !f(fd_HypergridNode_starttime, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_HypergridNode_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_HypergridNode) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		return x.Pubkey != ""
	case "hypergridssn.hypergridssn.HypergridNode.name":
		return x.Name != ""
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		return x.Rpc != ""
	case "hypergridssn.hypergridssn.HypergridNode.role":
		return x.Role != int32(0)
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		return x.Starttime != int32(0)
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_HypergridNode) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		x.Pubkey = ""
	case "hypergridssn.hypergridssn.HypergridNode.name":
		x.Name = ""
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		x.Rpc = ""
	case "hypergridssn.hypergridssn.HypergridNode.role":
		x.Role = int32(0)
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		x.Starttime = int32(0)
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_HypergridNode) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		value := x.Pubkey
		return protoreflect.ValueOfString(value)
	case "hypergridssn.hypergridssn.HypergridNode.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		value := x.Rpc
		return protoreflect.ValueOfString(value)
	case "hypergridssn.hypergridssn.HypergridNode.role":
		value := x.Role
		return protoreflect.ValueOfInt32(value)
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		value := x.Starttime
		return protoreflect.ValueOfInt32(value)
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_HypergridNode) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		x.Pubkey = value.Interface().(string)
	case "hypergridssn.hypergridssn.HypergridNode.name":
		x.Name = value.Interface().(string)
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		x.Rpc = value.Interface().(string)
	case "hypergridssn.hypergridssn.HypergridNode.role":
		x.Role = int32(value.Int())
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		x.Starttime = int32(value.Int())
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_HypergridNode) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		panic(fmt.Errorf("field pubkey of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	case "hypergridssn.hypergridssn.HypergridNode.name":
		panic(fmt.Errorf("field name of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		panic(fmt.Errorf("field rpc of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	case "hypergridssn.hypergridssn.HypergridNode.role":
		panic(fmt.Errorf("field role of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		panic(fmt.Errorf("field starttime of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		panic(fmt.Errorf("field creator of message hypergridssn.hypergridssn.HypergridNode is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_HypergridNode) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "hypergridssn.hypergridssn.HypergridNode.pubkey":
		return protoreflect.ValueOfString("")
	case "hypergridssn.hypergridssn.HypergridNode.name":
		return protoreflect.ValueOfString("")
	case "hypergridssn.hypergridssn.HypergridNode.rpc":
		return protoreflect.ValueOfString("")
	case "hypergridssn.hypergridssn.HypergridNode.role":
		return protoreflect.ValueOfInt32(int32(0))
	case "hypergridssn.hypergridssn.HypergridNode.starttime":
		return protoreflect.ValueOfInt32(int32(0))
	case "hypergridssn.hypergridssn.HypergridNode.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: hypergridssn.hypergridssn.HypergridNode"))
		}
		panic(fmt.Errorf("message hypergridssn.hypergridssn.HypergridNode does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_HypergridNode) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in hypergridssn.hypergridssn.HypergridNode", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_HypergridNode) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_HypergridNode) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_HypergridNode) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_HypergridNode) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*HypergridNode)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Pubkey)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Rpc)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Role != 0 {
			n += 1 + runtime.Sov(uint64(x.Role))
		}
		if x.Starttime != 0 {
			n += 1 + runtime.Sov(uint64(x.Starttime))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*HypergridNode)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x32
		}
		if x.Starttime != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Starttime))
			i--
			dAtA[i] = 0x28
		}
		if x.Role != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Role))
			i--
			dAtA[i] = 0x20
		}
		if len(x.Rpc) > 0 {
			i -= len(x.Rpc)
			copy(dAtA[i:], x.Rpc)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Rpc)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Pubkey) > 0 {
			i -= len(x.Pubkey)
			copy(dAtA[i:], x.Pubkey)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Pubkey)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*HypergridNode)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: HypergridNode: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: HypergridNode: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Pubkey = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Rpc", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Rpc = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
				}
				x.Role = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Role |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Starttime", wireType)
				}
				x.Starttime = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Starttime |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: hypergridssn/hypergridssn/hypergrid_node.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HypergridNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey    string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // Grid's pubkey
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rpc       string `protobuf:"bytes,3,opt,name=rpc,proto3" json:"rpc,omitempty"`    // Grid RPC
	Role      int32  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"` // 0: unknown, 1: Solana L1, 2: SSN, 3: Grid, 4: Sonic Grid
	Starttime int32  `protobuf:"varint,5,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Creator   string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *HypergridNode) Reset() {
	*x = HypergridNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypergridssn_hypergridssn_hypergrid_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergridNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergridNode) ProtoMessage() {}

// Deprecated: Use HypergridNode.ProtoReflect.Descriptor instead.
func (*HypergridNode) Descriptor() ([]byte, []int) {
	return file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescGZIP(), []int{0}
}

func (x *HypergridNode) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *HypergridNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HypergridNode) GetRpc() string {
	if x != nil {
		return x.Rpc
	}
	return ""
}

func (x *HypergridNode) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *HypergridNode) GetStarttime() int32 {
	if x != nil {
		return x.Starttime
	}
	return 0
}

func (x *HypergridNode) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_hypergridssn_hypergridssn_hypergrid_node_proto protoreflect.FileDescriptor

var file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x2f, 0x68,
	0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x2f, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x19, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x2e, 0x68,
	0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x0d,
	0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x70, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x70, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xe4, 0x01, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e,
	0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x2e, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x42, 0x12, 0x48, 0x79, 0x70, 0x65, 0x72,
	0x67, 0x72, 0x69, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x2a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x2f, 0x68,
	0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0xa2, 0x02, 0x03, 0x48, 0x48,
	0x58, 0xaa, 0x02, 0x19, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e,
	0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0xca, 0x02, 0x19,
	0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x5c, 0x48, 0x79, 0x70,
	0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0xe2, 0x02, 0x25, 0x48, 0x79, 0x70, 0x65,
	0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x5c, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72,
	0x69, 0x64, 0x73, 0x73, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x1a, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e,
	0x3a, 0x3a, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x69, 0x64, 0x73, 0x73, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescOnce sync.Once
	file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescData = file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDesc
)

func file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescGZIP() []byte {
	file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescOnce.Do(func() {
		file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescData)
	})
	return file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDescData
}

var file_hypergridssn_hypergridssn_hypergrid_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hypergridssn_hypergridssn_hypergrid_node_proto_goTypes = []interface{}{
	(*HypergridNode)(nil), // 0: hypergridssn.hypergridssn.HypergridNode
}
var file_hypergridssn_hypergridssn_hypergrid_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hypergridssn_hypergridssn_hypergrid_node_proto_init() }
func file_hypergridssn_hypergridssn_hypergrid_node_proto_init() {
	if File_hypergridssn_hypergridssn_hypergrid_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hypergridssn_hypergridssn_hypergrid_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergridNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypergridssn_hypergridssn_hypergrid_node_proto_goTypes,
		DependencyIndexes: file_hypergridssn_hypergridssn_hypergrid_node_proto_depIdxs,
		MessageInfos:      file_hypergridssn_hypergridssn_hypergrid_node_proto_msgTypes,
	}.Build()
	File_hypergridssn_hypergridssn_hypergrid_node_proto = out.File
	file_hypergridssn_hypergridssn_hypergrid_node_proto_rawDesc = nil
	file_hypergridssn_hypergridssn_hypergrid_node_proto_goTypes = nil
	file_hypergridssn_hypergridssn_hypergrid_node_proto_depIdxs = nil
}
