// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hypergridssn/hypergridssn/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the hypergridssn module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params                 Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	SolanaAccountList      []SolanaAccount     `protobuf:"bytes,2,rep,name=solanaAccountList,proto3" json:"solanaAccountList"`
	GridBlockFeeList       []GridBlockFee      `protobuf:"bytes,5,rep,name=gridBlockFeeList,proto3" json:"gridBlockFeeList"`
	GridBlockFeeCount      uint64              `protobuf:"varint,6,opt,name=gridBlockFeeCount,proto3" json:"gridBlockFeeCount,omitempty"`
	HypergridNodeList      []HypergridNode     `protobuf:"bytes,7,rep,name=hypergridNodeList,proto3" json:"hypergridNodeList"`
	FeeSettlementBillList  []FeeSettlementBill `protobuf:"bytes,8,rep,name=feeSettlementBillList,proto3" json:"feeSettlementBillList"`
	FeeSettlementBillCount uint64              `protobuf:"varint,9,opt,name=feeSettlementBillCount,proto3" json:"feeSettlementBillCount,omitempty"`
	GridInboxList          []GridInbox         `protobuf:"bytes,10,rep,name=gridInboxList,proto3" json:"gridInboxList"`
	GridInboxCount         uint64              `protobuf:"varint,11,opt,name=gridInboxCount,proto3" json:"gridInboxCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f99cb2cfe84cae46, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSolanaAccountList() []SolanaAccount {
	if m != nil {
		return m.SolanaAccountList
	}
	return nil
}

func (m *GenesisState) GetGridBlockFeeList() []GridBlockFee {
	if m != nil {
		return m.GridBlockFeeList
	}
	return nil
}

func (m *GenesisState) GetGridBlockFeeCount() uint64 {
	if m != nil {
		return m.GridBlockFeeCount
	}
	return 0
}

func (m *GenesisState) GetHypergridNodeList() []HypergridNode {
	if m != nil {
		return m.HypergridNodeList
	}
	return nil
}

func (m *GenesisState) GetFeeSettlementBillList() []FeeSettlementBill {
	if m != nil {
		return m.FeeSettlementBillList
	}
	return nil
}

func (m *GenesisState) GetFeeSettlementBillCount() uint64 {
	if m != nil {
		return m.FeeSettlementBillCount
	}
	return 0
}

func (m *GenesisState) GetGridInboxList() []GridInbox {
	if m != nil {
		return m.GridInboxList
	}
	return nil
}

func (m *GenesisState) GetGridInboxCount() uint64 {
	if m != nil {
		return m.GridInboxCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hypergridssn.hypergridssn.GenesisState")
}

func init() {
	proto.RegisterFile("hypergridssn/hypergridssn/genesis.proto", fileDescriptor_f99cb2cfe84cae46)
}

var fileDescriptor_f99cb2cfe84cae46 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4f, 0x8f, 0xd2, 0x40,
	0x14, 0x6f, 0x75, 0x17, 0xdd, 0x41, 0x8d, 0x4c, 0xd4, 0x20, 0x87, 0x8a, 0x1b, 0xb3, 0xdb, 0x10,
	0x2c, 0x09, 0x24, 0x9e, 0xbc, 0x58, 0x0d, 0x68, 0x62, 0x0c, 0x81, 0x93, 0xc6, 0xa4, 0x69, 0xe1,
	0x51, 0x1a, 0xcb, 0x4c, 0xd3, 0x19, 0x13, 0xf8, 0x16, 0x7e, 0x0c, 0x8f, 0x5e, 0xfc, 0x0e, 0x1c,
	0x39, 0x7a, 0x32, 0x06, 0x0e, 0x7e, 0x0d, 0x33, 0x33, 0xa5, 0x29, 0xd4, 0xd2, 0x0b, 0x74, 0xde,
	0xfb, 0xfd, 0x7b, 0xaf, 0x53, 0x74, 0x3d, 0x5f, 0x45, 0x10, 0xfb, 0x71, 0x30, 0x65, 0x8c, 0x74,
	0x0e, 0x0e, 0x3e, 0x10, 0x60, 0x01, 0xb3, 0xa2, 0x98, 0x72, 0x8a, 0x1f, 0x67, 0x7b, 0x56, 0xf6,
	0xd0, 0xa8, 0xb9, 0x8b, 0x80, 0xd0, 0x8e, 0xfc, 0x55, 0xe8, 0xc6, 0x03, 0x9f, 0xfa, 0x54, 0x3e,
	0x76, 0xc4, 0x53, 0x52, 0xbd, 0x2a, 0x36, 0x8b, 0xdc, 0xd8, 0x5d, 0x24, 0x5e, 0x0d, 0xab, 0x18,
	0xc7, 0x68, 0xe8, 0x12, 0xd7, 0x71, 0x27, 0x13, 0xfa, 0x95, 0xf0, 0x72, 0xbc, 0xf8, 0x77, 0xbc,
	0x90, 0x4e, 0xbe, 0x38, 0x33, 0x80, 0x72, 0x7c, 0x7a, 0x70, 0x08, 0x9d, 0xee, 0xf1, 0xbd, 0x62,
	0xfc, 0x0c, 0xc0, 0x61, 0xc0, 0x79, 0x08, 0x0b, 0x20, 0xdc, 0xf1, 0x82, 0x30, 0x4c, 0x48, 0xad,
	0x92, 0x50, 0x01, 0xf1, 0xe8, 0x52, 0x61, 0x2f, 0x7f, 0x9e, 0xa3, 0x3b, 0x03, 0xb5, 0xee, 0x31,
	0x77, 0x39, 0xe0, 0x37, 0xa8, 0xa2, 0x36, 0x52, 0xd7, 0x9b, 0xba, 0x59, 0xed, 0x3e, 0xb5, 0x0a,
	0xd7, 0x6f, 0x0d, 0x25, 0xd0, 0xbe, 0x58, 0xff, 0x7e, 0xa2, 0x7d, 0xff, 0xfb, 0xa3, 0xa5, 0x8f,
	0x12, 0x2e, 0xfe, 0x8c, 0x6a, 0x6a, 0x5f, 0xaf, 0xd4, 0xba, 0xde, 0x07, 0x8c, 0xd7, 0x6f, 0x34,
	0x6f, 0x9a, 0xd5, 0xae, 0x79, 0x42, 0x70, 0x9c, 0xe5, 0xd8, 0x67, 0x42, 0x77, 0x94, 0x17, 0xc2,
	0x1f, 0xd1, 0x7d, 0xc1, 0xb0, 0xc5, 0x72, 0xfb, 0x00, 0x52, 0xfc, 0x5c, 0x8a, 0x5f, 0x9f, 0x10,
	0x1f, 0x64, 0x28, 0x89, 0x76, 0x4e, 0x06, 0xb7, 0x51, 0x2d, 0x5b, 0x7b, 0x2d, 0x3c, 0xeb, 0x95,
	0xa6, 0x6e, 0x9e, 0x8d, 0xf2, 0x0d, 0x31, 0x66, 0x6a, 0xf1, 0x81, 0x4e, 0x55, 0x92, 0x5b, 0xa5,
	0x63, 0xbe, 0xcd, 0x72, 0xf6, 0x63, 0xe6, 0x84, 0xf0, 0x1c, 0x3d, 0x9c, 0x01, 0x8c, 0xd3, 0x77,
	0x6c, 0x07, 0x61, 0x28, 0x1d, 0x6e, 0x4b, 0x87, 0xf6, 0x09, 0x87, 0xfe, 0x31, 0x2f, 0x71, 0xf9,
	0xbf, 0x20, 0x7e, 0x81, 0x1e, 0xe5, 0x1a, 0x6a, 0xf4, 0x0b, 0x39, 0x7a, 0x41, 0x17, 0x0f, 0xd1,
	0x5d, 0xe1, 0xf8, 0x4e, 0x5c, 0x28, 0x99, 0x0c, 0xc9, 0x64, 0xcf, 0x4a, 0xde, 0x82, 0xc4, 0x27,
	0x89, 0x0e, 0x05, 0xf0, 0x15, 0xba, 0x97, 0x16, 0x54, 0x82, 0xaa, 0x4c, 0x70, 0x54, 0xb5, 0x5f,
	0xae, 0xb7, 0x86, 0xbe, 0xd9, 0x1a, 0xfa, 0x9f, 0xad, 0xa1, 0x7f, 0xdb, 0x19, 0xda, 0x66, 0x67,
	0x68, 0xbf, 0x76, 0x86, 0xf6, 0xe9, 0x32, 0xb5, 0x7b, 0x2e, 0x6e, 0xfc, 0xf2, 0xf0, 0x03, 0xe0,
	0xab, 0x08, 0x98, 0x57, 0x91, 0x97, 0xbf, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x35, 0x26,
	0xa4, 0x84, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GridInboxCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GridInboxCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.GridInboxList) > 0 {
		for iNdEx := len(m.GridInboxList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GridInboxList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.FeeSettlementBillCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.FeeSettlementBillCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.FeeSettlementBillList) > 0 {
		for iNdEx := len(m.FeeSettlementBillList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeSettlementBillList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.HypergridNodeList) > 0 {
		for iNdEx := len(m.HypergridNodeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HypergridNodeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.GridBlockFeeCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GridBlockFeeCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.GridBlockFeeList) > 0 {
		for iNdEx := len(m.GridBlockFeeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GridBlockFeeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SolanaAccountList) > 0 {
		for iNdEx := len(m.SolanaAccountList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SolanaAccountList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.SolanaAccountList) > 0 {
		for _, e := range m.SolanaAccountList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GridBlockFeeList) > 0 {
		for _, e := range m.GridBlockFeeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GridBlockFeeCount != 0 {
		n += 1 + sovGenesis(uint64(m.GridBlockFeeCount))
	}
	if len(m.HypergridNodeList) > 0 {
		for _, e := range m.HypergridNodeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FeeSettlementBillList) > 0 {
		for _, e := range m.FeeSettlementBillList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.FeeSettlementBillCount != 0 {
		n += 1 + sovGenesis(uint64(m.FeeSettlementBillCount))
	}
	if len(m.GridInboxList) > 0 {
		for _, e := range m.GridInboxList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GridInboxCount != 0 {
		n += 1 + sovGenesis(uint64(m.GridInboxCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SolanaAccountList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SolanaAccountList = append(m.SolanaAccountList, SolanaAccount{})
			if err := m.SolanaAccountList[len(m.SolanaAccountList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridBlockFeeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridBlockFeeList = append(m.GridBlockFeeList, GridBlockFee{})
			if err := m.GridBlockFeeList[len(m.GridBlockFeeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridBlockFeeCount", wireType)
			}
			m.GridBlockFeeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GridBlockFeeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HypergridNodeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HypergridNodeList = append(m.HypergridNodeList, HypergridNode{})
			if err := m.HypergridNodeList[len(m.HypergridNodeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSettlementBillList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeSettlementBillList = append(m.FeeSettlementBillList, FeeSettlementBill{})
			if err := m.FeeSettlementBillList[len(m.FeeSettlementBillList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSettlementBillCount", wireType)
			}
			m.FeeSettlementBillCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeSettlementBillCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridInboxList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridInboxList = append(m.GridInboxList, GridInbox{})
			if err := m.GridInboxList[len(m.GridInboxList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridInboxCount", wireType)
			}
			m.GridInboxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GridInboxCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
