// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hypergridssn/hypergridssn/hypergrid_member.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HypergridMember struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rpcurl   string `protobuf:"bytes,2,opt,name=rpcurl,proto3" json:"rpcurl,omitempty"`
	Role     int32  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	Jointime int32  `protobuf:"varint,4,opt,name=jointime,proto3" json:"jointime,omitempty"`
	Creator  string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *HypergridMember) Reset()         { *m = HypergridMember{} }
func (m *HypergridMember) String() string { return proto.CompactTextString(m) }
func (*HypergridMember) ProtoMessage()    {}
func (*HypergridMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_801292e71430c81c, []int{0}
}
func (m *HypergridMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HypergridMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HypergridMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HypergridMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HypergridMember.Merge(m, src)
}
func (m *HypergridMember) XXX_Size() int {
	return m.Size()
}
func (m *HypergridMember) XXX_DiscardUnknown() {
	xxx_messageInfo_HypergridMember.DiscardUnknown(m)
}

var xxx_messageInfo_HypergridMember proto.InternalMessageInfo

func (m *HypergridMember) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HypergridMember) GetRpcurl() string {
	if m != nil {
		return m.Rpcurl
	}
	return ""
}

func (m *HypergridMember) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *HypergridMember) GetJointime() int32 {
	if m != nil {
		return m.Jointime
	}
	return 0
}

func (m *HypergridMember) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*HypergridMember)(nil), "hypergridssn.hypergridssn.HypergridMember")
}

func init() {
	proto.RegisterFile("hypergridssn/hypergridssn/hypergrid_member.proto", fileDescriptor_801292e71430c81c)
}

var fileDescriptor_801292e71430c81c = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xc8, 0xa8, 0x2c, 0x48,
	0x2d, 0x4a, 0x2f, 0xca, 0x4c, 0x29, 0x2e, 0xce, 0xd3, 0xc7, 0xce, 0x89, 0xcf, 0x4d, 0xcd, 0x4d,
	0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x44, 0x56, 0xa4, 0x87, 0xcc, 0x51,
	0x6a, 0x66, 0xe4, 0xe2, 0xf7, 0x80, 0x09, 0xf8, 0x82, 0x35, 0x09, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0x15, 0x15,
	0x24, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x81, 0xc5, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x96, 0xa2, 0xfc,
	0x9c, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x8a, 0x8b, 0x23, 0x2b,
	0x3f, 0x33, 0xaf, 0x24, 0x33, 0x37, 0x55, 0x82, 0x05, 0x2c, 0x0e, 0xe7, 0x0b, 0x49, 0x70, 0xb1,
	0x27, 0x17, 0xa5, 0x26, 0x96, 0xe4, 0x17, 0x49, 0xb0, 0x82, 0x0d, 0x82, 0x71, 0x9d, 0x6c, 0x4e,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x09, 0xee, 0x5a, 0x5d, 0x90, 0x07,
	0x2b, 0x50, 0xfd, 0x5b, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xf6, 0xa5, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0xaf, 0xfe, 0x6c, 0x19, 0x01, 0x00, 0x00,
}

func (m *HypergridMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HypergridMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HypergridMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintHypergridMember(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Jointime != 0 {
		i = encodeVarintHypergridMember(dAtA, i, uint64(m.Jointime))
		i--
		dAtA[i] = 0x20
	}
	if m.Role != 0 {
		i = encodeVarintHypergridMember(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Rpcurl) > 0 {
		i -= len(m.Rpcurl)
		copy(dAtA[i:], m.Rpcurl)
		i = encodeVarintHypergridMember(dAtA, i, uint64(len(m.Rpcurl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintHypergridMember(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHypergridMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovHypergridMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HypergridMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovHypergridMember(uint64(l))
	}
	l = len(m.Rpcurl)
	if l > 0 {
		n += 1 + l + sovHypergridMember(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovHypergridMember(uint64(m.Role))
	}
	if m.Jointime != 0 {
		n += 1 + sovHypergridMember(uint64(m.Jointime))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovHypergridMember(uint64(l))
	}
	return n
}

func sovHypergridMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHypergridMember(x uint64) (n int) {
	return sovHypergridMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HypergridMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHypergridMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HypergridMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HypergridMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHypergridMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHypergridMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rpcurl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHypergridMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHypergridMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rpcurl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jointime", wireType)
			}
			m.Jointime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Jointime |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHypergridMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHypergridMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHypergridMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHypergridMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHypergridMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHypergridMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHypergridMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHypergridMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHypergridMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHypergridMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHypergridMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHypergridMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHypergridMember = fmt.Errorf("proto: unexpected end of group")
)
